### ISSUE TITLE
Error: Parse Error: unknown: Cannot read property 'decorators' of undefined

### ISSUE THREAD

**Issue by benNek** [GoogleChromeLabs/estimator.dev#6]
Running this tool on https://www.momondo.com/car-rental/Los-Angeles-16078 results in error popping up when analysing one of the bundles:

 ```
https://www.momondo.com/res/combined.js?v=0bd227628862ca7ee2b13184ffd76fd10bcf9cfe-exclude-keel-globals&cluster=4&tag=ui/seo/cars/city/CityCarsPage
Error: Parse Error: unknown: Cannot read property 'decorators' of undefined
    at runBabel ([worker eval]:49:13)
    at MessagePort.<anonymous> ([worker eval]:4:36)
    at MessagePort.emit (events.js:315:20)
    at MessagePort.onmessage (internal/worker/io.js:78:8)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)
```

It can be reproduced on every run.

**Comment by dreitzner** [comment]
Same for https://estimator.dev/#billa.at
